### ISSUE TITLE
use 5.008 with say in examples

### ISSUE THREAD

**Issue by jibsheet** [maxmind/GeoIP2-perl#12]
It looks like in 66508b3 when docs for models were added, the SYNOPSIS of a bunch of modules got use v5.10; .... say $city->name (or something similar).

However, shortly thereafter, in eca0d8d and then fc76c4b those use v5.10 lines got switched to 5.008(008) because of some backwards compatibility work.

However, this means the SYNOPSIS code for a bunch of modules now says

use 5.008;
...
say $something->name();
which doesn't work

Would a PR that just did s/say/print/ be good or did you want to have the more modern example and fix the use line?

-kevin

**Comment by autarch** [comment]
Fixed in the latest release, thank!
