### ISSUE TITLE
Switch to JSON::MaybeXS

### ISSUE THREAD

**Issue by oschwald** [maxmind/GeoIP2-perl#17]
JSON::MaybeXS provides the same functionality as JSON, is better maintained, and tries to use Cpanel::JSON::XS before JSON::XS.

**Comment by 2shortplanks** [comment]
I'm not sure I agree with this. If JSON::XS is good enough then we should stick with it. If it's not good enough - and being not maintained it probably isn't long term - then we should move away from it.

JSON::MaybeXS also has unpredictable behaviour depending on what other code is used (it'll stick with JSON::XS if it's already loaded.). This might present us with odd support issues.

Finally JSON::MaybeXS will fall back to JSON::PP. is this going to itself introduce bugs?  Is the fact that it only recommends rather requires an XS implementation mean that installations are going to be stuck with a slow pure Perl implement of JSON parsing?

**Comment by oschwald** [comment]
We do not use JSON::XS directly. We use [JSON](https://metacpan.org/pod/JSON), which has similar behavior to JSON::MaybeXS. The reason for this is that we don't want an XS dep.

**Comment by oalders** [comment]
:+1:
