### ISSUE TITLE
Very, very slow

### ISSUE THREAD

**Issue by zdm** [maxmind/GeoIP2-perl#25]
Why it is so slow in comparison with old GeoIP?

```
GeoIP2 - xs   6197/s     --        -70%    -99%
GeoIP - pp    20698/s    234%      --      -97%
GeoIP - xs    680613/s   10883%    3188%   --
```

**Comment by autarch** [comment]
It's hard to comment without seeing your benchmark script. Part of the slowness is inherent in the much more flexible data structure in the new MaxMind DB format, which allows us to easily add new fields to a database in the future.

Also, are you sure you're actually using the XS version of MaxMind::DB::Reader, `MaxMind::DB::Reader::XS`?

**Comment by zdm** [comment]
Hi. I am sure, that I use XS. Without XS speed is ~ 200 / sec.

Here is the code, what I am use:
```
use feature qw[:all];
use Benchmark;
use Geo::IP::PurePerl;
use Geo::IP;
use GeoIP2::Database::Reader;

my $geoip_pp = Geo::IP::PurePerl->open( 'geoip_country.dat', 0 );    # no cache

my $geoip_xs = Geo::IP->open( 'geoip_country.dat', 0 );              # no cache

my $geoip2_xs = GeoIP2::Database::Reader->new(
    file    => 'geoip2_country.dat',
    locales => ['en'],
);

my $ip = '192.37.51.100';

my $t = {
    geoip_pp => sub {
        return $geoip_pp->country_code_by_addr($ip);
    },
    geoip_xs => sub {
        return $geoip_xs->country_code_by_addr($ip);
    },
    geoip2_xs => sub {
        return $geoip2_xs->country( ip => $ip );
    },
};

Benchmark::cmpthese( Benchmark::timethese( -3, $t ) );

1;
__END__
```

**Comment by autarch** [comment]
I think there's a few things going on here.

* The GeoIP Legacy Country database is almost certainly the fastest database to access. It has very few fields (IIRC it may have exactly one field, in fact), and they are all fixed length. Much of the data available from the database is actually hardcoded in static arrays in the underlying C or Perl library.
* GeoIP2 uses a new, much more flexible format called MaxMind DB format. The downside of the flexibility is that the fastest possible case will always be slower than the old, fixed-length field format. The upside is that we include a lot more data, easily support IPv6, and can add new data in future releases without breaking existing APIs.
* The Perl library isn't well optimized, so it's probably slower than it needs to be. Unfortunately, this API isn't as widely used as some other libraries (especially PHP and Java), so it gets less attention. 

Patches to improve performance without breaking backwards compatibility would certainly be welcome. If you're interested in looking into it, I would suggest starting with the [MaxMind::DB::Reader::XS](https://github.com/maxmind/MaxMind-DB-Reader-XS) distribution. The GeoIP2 library uses this under the hood. I'm not sure if that's the bottleneck or not.

Also, as an aside, I see that you've renamed the database files you're using. I wouldn't recommend that. We've actually gone to the trouble of registering a MIME type for the `.mmdb` extension (http://www.iana.org/assignments/media-types/application/vnd.maxmind.maxmind-db). In addition, if you use our [geoipupdate](http://dev.maxmind.com/geoip/geoipupdate/) tool, which you can use with the free GeoLite databases, it expects to find files matching the names under which we distribute them. Changing the file names is just asking for trouble.

**Comment by zdm** [comment]
Hi, Dave.

Thanks for reply.

I will see, what I can do.

1. Moo constructors can be accelerated;
2. pure perl isa in Moo attributes can affect performance significantly,
better to use Type::Tiny, which use XS for most of simple types;

**Comment by filimonov** [comment]
All that objects wrappers around MaxMind::DB::Reader gives mostly nothing to usablility, but make that very -very slow. 

Check that simple benchmark https://gist.github.com/filimonov/4bd178fc9578837bf25c613887586442

**Comment by zdm** [comment]
Even if MaxMind::DB::Reader::XS used directly - it is still slow. 60k/sec vs 1200k/sec for Geo::IP.
Pure perl version MaxMind::DB::Reader - is not usable at all - 200/sec, because it uses Moo ans access to the attributes via methods calls, that is extremely slow (good example of over engineered software).

**Comment by oschwald** [comment]
Closing as we are no longer making enhancements to this module.
