### ISSUE TITLE
Is the test dependency on Code::TidyAll::Plugin::SortLines::Naturally needed?

### ISSUE THREAD

**Issue by Grinnz** [maxmind/GeoIP2-perl#35]
As far as I can tell, Code::TidyAll is not used in any tests, other than generated author and release tests which are not run by users. This introduces a significant dependency tree to the distribution. If it is needed for author or release testing, it should be a DevelopRequires prereq.

**Comment by oschwald** [comment]
Thanks for pointing that out. It indeed should be a develop dependency.

**Comment by oschwald** [comment]
Fixed in a4065b2968f2351ef9ab4467ffdd777557c3dedb
