### ISSUE TITLE
FYI latest release has additional test/requires of Code::TidyAll::Plugin::SortLines::Naturally

### ISSUE THREAD

**Issue by DannyThomas** [maxmind/GeoIP2-perl#36]
presumably for release-tidyall.t but that hasn't changed

is there a way of grouping release test requirements away from the
test requirements needed for a user installing this distribution ?

**Comment by oschwald** [comment]
Thanks for the report. This has already been fixed in a4065b2968f2351ef9ab4467ffdd777557c3dedb. We will likely do a release with the fix today.
