### ISSUE TITLE
Is there a ppa version ?

### ISSUE THREAD

**Issue by waghanza** [maxmind/GeoIP2-perl#47]
Hello,

I use `perl` binding to read **mmdb** files. 

It will be awesome if I could test my `perl` scripts using https://travis-ci.com.

Is there any ubuntu package available on maxmind **ppa* ?

Regards,

**Comment by oschwald** [comment]
We currently do not provide Ubuntu packages for the Perl API. Travis, however, supports installing CPAN modules when using the `perl` language.

**Comment by waghanza** [comment]
@oschwald Strange, working on a `perl` base project https://travis-ci.org/waghanza/routing/builds/228844812, but not on a private rails based project

Closing this issue since working
