### ISSUE TITLE
Returning country subdivision

### ISSUE THREAD

**Issue by waghanza** [maxmind/GeoIP2-perl#49]
Hello,

Is there a way to get the country subdision (https://en.wikipedia.org/wiki/ISO_3166-2) from `GeoLite2-Country.mmdb` ?

For example :

+ FR-MQ  https://en.wikipedia.org/wiki/Martinique
+ UY-CA for https://en.wikipedia.org/wiki/Canelones_Department

Regards,

**Comment by oschwald** [comment]
Yes, you can access it at `$record->most_specific_subdivision->iso_code`. There may be more than one level of subdivisions for a location; if you want something other than the most specific, use `->subdivisions` instead. The value is only the second half of the ISO 3166-2 code, i.e., after the `-`. If you want the 3166-1 prefix, you will have to get that from `$record->country->iso_code`.
