### ISSUE TITLE
GeoIP2 Perl 6 reader is ready.

### ISSUE THREAD

**Issue by bbkr** [maxmind/GeoIP2-perl#65]
I'm happy to announce that I've finished working on Perl 6 version of GeoIP2 databases reader: https://github.com/bbkr/GeoIP2 . It can locate IPv4 and IPv6 in every database that MaxMind currently offers.

It's released under `GeoIP2:auth<bbkr>` namespace,  so if you ever decide to write your own reader there will be no namespaces collision (Perl 6 allows multiple authors to publish under exactly the same namespace and even install such modules side by side).

Please add this module to your APIs list: https://dev.maxmind.com/geoip/geoip2/downloadable/#MaxMind_APIs

Thanks!

**Comment by oschwald** [comment]
Excellent! Thank you for working on this. I'll add it to the list now.
