### ISSUE TITLE
Doesn't install on 5.8.8

### ISSUE THREAD

**Issue by tlhackque** [maxmind/GeoIP2-perl#70]
[Your doc](https://metacpan.org/release/GeoIP2/source/lib/GeoIP2.pm) says that GeoIP2 has been tested on 5.8.8.

However, GeoIP2 depends on MaxMind::DB::Reader 1.000000, which requires Perl 5.10.

Thus, install fails to install the dependency, and the GeoIP2 tests fail.

Perhaps your testing was with an earlier version of MaxMind::DB::Reader?

**Comment by oschwald** [comment]
Thanks. As you noted, the documentation is outdated.
