### ISSUE TITLE
web-service-request script has too generic name

### ISSUE THREAD

**Issue by ppisar** [maxmind/GeoIP2-perl#78]
GeoIP2-2.006002 distribution installs a web-service-request script. That name is not a good one for a system-wide program, because there can be many other software packages that might want to install a script for requesting a web service.

I recommend renaming the script to geoip2-web-service-request.

**Comment by oschwald** [comment]
I agree. I'm not entirely sure what the initial intent was with that script. Given the use of `use lib` and its limited utility, I suspect the intent was for it to be an example program rather than something installed with the package.

**Comment by oschwald** [comment]
I am closing this as the module has been deprecated and we are only fixing serious bugs at this point.
